language: generic
sudo: required
services:
    - docker


before_install:
    - docker build -t surya/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true surya/react-test npm test

after_success:
    - docker build -t surya/multi-client ./client
    - docker build -t surya/multi-nginx ./nginx
    - docker build -t surya/multi-server ./server
    - docker build -t surya/multi-worker ./worker
    # login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push surya/multi-client
    - docker push surya/multi-nginx
    - docker push surya/multi-server
    - docker push surya/multi-worker 

deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'multi-docker'
    env: 'MultiDocker-env-1'
    bucket_name: 'elasticbeanstalk-us-east-2-486921882652'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
